- name: Run database container
  community.docker.docker_container:
    name: postgres-db
    image: camillepech/tp-devops-postgres
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_DB: "{{ db_name }}"
    networks:
      - name: my_network
# tasks file for roles/database
