- name: Run backend container
  community.docker.docker_container:
    name: backend
    image: camillepech/tp-devops-simple-api:latest
    pull: true
    state: started
    restart_policy: always
    env:
      DB_HOST: "postgres-db"
      DB_USER: "usr"
      DB_PASSWORD: "pwd"
      DB_NAME: "db"
    networks:
      - name: my_network